[package]
name = "actnet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
device-cuda = {version="*", path="./device-cuda"}
device-api = {version="*", path="./device-api"}