[package]
name = "rt-interpret"
version = "0.1.0"
edition = "2021"
description = "a serial interpreter for ir-linajbr, serving as a standard toy model"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
