[package]
name = "ir-linajbr-macro"
version = "0.1.0"
edition = "2021"
autotests = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
ir-linajbr-core = {path="../ir-linajbr-core"}
lazy_static = "1.4.0"